// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6TilaiXuvr-aNYOJPw1s2qlryrjm3Ols',
    appId: '1:392448934525:web:32b0b8511b64289a39a714',
    messagingSenderId: '392448934525',
    projectId: 'grupo-ramos--lf',
    authDomain: 'grupo-ramos--lf.firebaseapp.com',
    storageBucket: 'grupo-ramos--lf.appspot.com',
    measurementId: 'G-FT78CRV82C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZlvNAl1o-BURrZaxFX5Z0ahMHVE2JNSU',
    appId: '1:392448934525:android:4beb6496b7a4bbf939a714',
    messagingSenderId: '392448934525',
    projectId: 'grupo-ramos--lf',
    storageBucket: 'grupo-ramos--lf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmi4vgY-1VK0gHkvnMHQjwBqe-WQedF08',
    appId: '1:392448934525:ios:3fbda39308aafbb139a714',
    messagingSenderId: '392448934525',
    projectId: 'grupo-ramos--lf',
    storageBucket: 'grupo-ramos--lf.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmi4vgY-1VK0gHkvnMHQjwBqe-WQedF08',
    appId: '1:392448934525:ios:dc01e31b2fce57af39a714',
    messagingSenderId: '392448934525',
    projectId: 'grupo-ramos--lf',
    storageBucket: 'grupo-ramos--lf.appspot.com',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );
}
